### ISSUE TITLE
我这边下载完插入图片并不显示

### ISSUE THREAD

**Issue by dm22933** [Beckjiang/imageCompress#1]
没有修改代码，但是下面图片并不显示
![tim 20170506095310](https://cloud.githubusercontent.com/assets/26136524/25769013/1698dfb4-3242-11e7-9a50-240e1aa5c917.png)

**Comment by jiangzhannan** [comment]
> 没有修改代码，但是下面图片并不显示
>代码里取得图片真实的高度和宽度只有在图片加载完的时候才有效

**Comment by Beckjiang** [comment]
> > 没有修改代码，但是下面图片并不显示
> > 代码里取得图片真实的高度和宽度只有在图片加载完的时候才有效

说得对，处理了一下。现在应该能用:)

**Comment by Beckjiang** [comment]
done.
